services:
  via-api:
    build: .
    image: via-api:latest
    container_name: via-api
    restart: unless-stopped
    #ports:
    #  - "8079:8079"
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./checkpoints:/usr/app/checkpoints