# Kafka configuration
kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=meta_data_update
spring.kafka.consumer.auto-offset-reset=earliest
kafka.topic.name=update_meta_data
spring.cloud.stream.function.autodetect=false

unity.catalog.name=aialabs
unity.catalog.schema.name=dg_dev
unity.catalog.table.name=data_table

unity.storage.bucket=s3://your-bucket/path/to/table

# Unity Catalog configuration
unity.catalog.api.url=http://localhost:8080/api/2.1/unity-catalog/tables/
unity.catalog.table.fullname=aialabs.dg_dev.data_table
spring.cloud.stream.bindings.metaDataUpdate-in-0.destination=meta_data_update
spring.cloud.stream.bindings.metaDataUpdate-in-0.group=config-consumer-group
# Logging settings (to suppress HttpClient debug logs)
logging.level.jdk.internal.httpclient.debug=INFO
logging.level.org.aialabs.dg.broker=DEBUG