detections:

  3:
    steps:
      - id: 13
        items:
          - case
          - mobile
      - id: 14
        items:
          - case
      - id: 15
        items:
          - flash
      - id: 0
        items: []
  2:
    steps:
      - id: 7
        items:
          - case
          - mobile
          # - charger
      - id: 8
        items:
          - case
      - id: 9
        items:
          - case
          - charger
      - id: 10
        items:
          - flash
      - id: 0
        items: []
  1:
    steps:
      - id: 1
        items:
          - case
          - mobile
          # - charger
      - id: 2
        items:
          - case
      - id: 3
        items:
          - case
          - charger
      - id: 4
        items:
          - flash
      - id: 0
        items: []
  0:
    steps:
      - id: 1
        items:
          - paper
      - id: 0
        items: []
  4:
    steps:
      - id: 16
        items:
          - person
      - id: 17
        items:
          - adhar
      - id: 18
        items:
          - pan card
      - id: 19
        items: []