models:
  - manuals:
      - name: "phone"
        ids:
          - 2
          - 1
          - 3
          - 5
          - 7
      - name: "ekyc"
        ids:
          - 4
          - 6
          - 8
      - name: "chair"
        ids:
          - 11
